-- Nexus · Diagnóstico Empresarial fixo
--
-- Instalação nova: execute este arquivo manualmente no PostgreSQL/Neon.
-- O catálogo, as fórmulas e as recomendações ficam em lib/diagnosticCatalog.js.
-- Este banco armazena somente dados gerados pelo uso do sistema.

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('nexus:diagnostics:fixed:v1'));

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS diagnostic_submission (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  status varchar(30) NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'submitted', 'under_review', 'completed', 'archived')),
  company_name varchar(255) NOT NULL,
  company_document varchar(30),
  respondent_name varchar(255),
  respondent_email varchar(255),
  respondent_phone varchar(40),
  diagnostic_date date NOT NULL DEFAULT current_date,
  created_by_user_id integer REFERENCES "user"(id) ON DELETE SET NULL,
  assigned_to_user_id integer REFERENCES "user"(id) ON DELETE SET NULL,
  reviewed_by_user_id integer REFERENCES "user"(id) ON DELETE SET NULL,
  consent_accepted_at timestamptz,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  CHECK (btrim(company_name) <> ''),
  CHECK (company_document IS NULL OR btrim(company_document) <> ''),
  CHECK (respondent_email IS NULL OR respondent_email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')
);

CREATE INDEX IF NOT EXISTS diagnostic_submission_status_created_idx
  ON diagnostic_submission(status, created_at DESC);
CREATE INDEX IF NOT EXISTS diagnostic_submission_company_name_idx
  ON diagnostic_submission(lower(company_name));
CREATE INDEX IF NOT EXISTS diagnostic_submission_date_idx
  ON diagnostic_submission(diagnostic_date DESC);

CREATE TABLE IF NOT EXISTS diagnostic_section_response (
  submission_id bigint NOT NULL REFERENCES diagnostic_submission(id) ON DELETE CASCADE,
  section_code varchar(30) NOT NULL,
  answers_responsible_name varchar(255),
  sector_responsible_name varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (submission_id, section_code),
  CHECK (section_code IN (
    'societario', 'tecnologia', 'comercial', 'marketing', 'financeiro',
    'controladoria', 'fiscal', 'contabil', 'gestao_pessoas', 'estrategia'
  ))
);

CREATE TABLE IF NOT EXISTS diagnostic_answer (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id bigint NOT NULL REFERENCES diagnostic_submission(id) ON DELETE CASCADE,
  question_code varchar(20) NOT NULL,
  applicable boolean NOT NULL DEFAULT false,
  self_score numeric(8,2) CHECK (self_score IS NULL OR self_score BETWEEN 0 AND 10),
  evaluation_code varchar(80),
  consultant_observation text,
  possible_improvements text,
  answered_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (submission_id, question_code),
  CHECK (question_code ~ '^(1\.[1-6]|2\.[1-5]|3\.[1-6]|4\.[1-3]|5\.[1-7]|6\.[1-9]|7\.[1-4]|8\.[1-4]|9\.[1-4]|10\.[1-3])$'),
  CHECK (evaluation_code IS NULL OR evaluation_code IN (
    'nao_existe', 'informal', 'padronizada', 'perfeita'
  ))
);

CREATE INDEX IF NOT EXISTS diagnostic_answer_submission_idx
  ON diagnostic_answer(submission_id);
CREATE INDEX IF NOT EXISTS diagnostic_answer_reviewed_idx
  ON diagnostic_answer(submission_id, evaluation_code);

CREATE TABLE IF NOT EXISTS diagnostic_section_result (
  submission_id bigint NOT NULL REFERENCES diagnostic_submission(id) ON DELETE CASCADE,
  section_code varchar(30) NOT NULL,
  self_score_sum numeric(14,4) NOT NULL DEFAULT 0 CHECK (self_score_sum >= 0),
  consultant_score_sum numeric(14,4) NOT NULL DEFAULT 0 CHECK (consultant_score_sum >= 0),
  max_score_sum numeric(14,4) NOT NULL DEFAULT 0 CHECK (max_score_sum >= 0),
  score_ratio numeric(14,12) NOT NULL DEFAULT 0 CHECK (score_ratio BETWEEN 0 AND 1),
  gap_ratio numeric(14,12) GENERATED ALWAYS AS (1::numeric - score_ratio) STORED,
  calculation_code varchar(80) NOT NULL DEFAULT 'diagnostico_empresarial_fixo_v1',
  calculated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (submission_id, section_code),
  CHECK (section_code IN (
    'societario', 'tecnologia', 'comercial', 'marketing', 'financeiro',
    'controladoria', 'fiscal', 'contabil', 'gestao_pessoas', 'estrategia'
  )),
  CHECK (btrim(calculation_code) <> '')
);

CREATE TABLE IF NOT EXISTS diagnostic_submission_result (
  submission_id bigint PRIMARY KEY REFERENCES diagnostic_submission(id) ON DELETE CASCADE,
  overall_score_ratio numeric(14,12) NOT NULL DEFAULT 0 CHECK (overall_score_ratio BETWEEN 0 AND 1),
  growth_pillars_ratio numeric(14,12) NOT NULL DEFAULT 0 CHECK (growth_pillars_ratio BETWEEN 0 AND 1),
  section_count smallint NOT NULL DEFAULT 10 CHECK (section_count = 10),
  growth_pillar_count smallint NOT NULL DEFAULT 4 CHECK (growth_pillar_count = 4),
  calculation_code varchar(80) NOT NULL DEFAULT 'diagnostico_empresarial_fixo_v1',
  calculated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (btrim(calculation_code) <> '')
);

CREATE TABLE IF NOT EXISTS diagnostic_protocol (
  submission_id bigint PRIMARY KEY REFERENCES diagnostic_submission(id) ON DELETE CASCADE,
  recipient_company_name varchar(255) NOT NULL,
  recipient_company_document varchar(30),
  recipient_address text,
  consultant_company_name varchar(255),
  consultant_company_document varchar(30),
  city varchar(120),
  state varchar(2),
  delivery_date date,
  signer_name varchar(255),
  signed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (btrim(recipient_company_name) <> ''),
  CHECK (state IS NULL OR state ~ '^[A-Z]{2}$')
);

CREATE OR REPLACE FUNCTION diagnostic_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS diagnostic_submission_touch_updated_at ON diagnostic_submission;
CREATE TRIGGER diagnostic_submission_touch_updated_at
BEFORE UPDATE ON diagnostic_submission
FOR EACH ROW EXECUTE FUNCTION diagnostic_touch_updated_at();

DROP TRIGGER IF EXISTS diagnostic_section_response_touch_updated_at ON diagnostic_section_response;
CREATE TRIGGER diagnostic_section_response_touch_updated_at
BEFORE UPDATE ON diagnostic_section_response
FOR EACH ROW EXECUTE FUNCTION diagnostic_touch_updated_at();

DROP TRIGGER IF EXISTS diagnostic_answer_touch_updated_at ON diagnostic_answer;
CREATE TRIGGER diagnostic_answer_touch_updated_at
BEFORE UPDATE ON diagnostic_answer
FOR EACH ROW EXECUTE FUNCTION diagnostic_touch_updated_at();

DROP TRIGGER IF EXISTS diagnostic_protocol_touch_updated_at ON diagnostic_protocol;
CREATE TRIGGER diagnostic_protocol_touch_updated_at
BEFORE UPDATE ON diagnostic_protocol
FOR EACH ROW EXECUTE FUNCTION diagnostic_touch_updated_at();

COMMIT;
