-- Nexus · Diagnóstico Empresarial v1
-- Fonte canônica: diagnóstico geral.xlsx
-- SHA-256: dd4c7b65010d0280825e2b8df091c35eb05cd394ff4a92d260f11d6fd4545425
-- Execute este arquivo manualmente no PostgreSQL/Neon. O app não o executa.

BEGIN;

-- Impede duas execuções concorrentes da mesma migration.
SELECT pg_advisory_xact_lock(hashtext('nexus:diagnostics:v1'));

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS diagnostic_template (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar(100) NOT NULL UNIQUE,
  name varchar(180) NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (btrim(slug) <> ''),
  CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS diagnostic_version (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id bigint NOT NULL REFERENCES diagnostic_template(id),
  version_number integer NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'retired')),
  is_active boolean NOT NULL DEFAULT false,
  title varchar(255) NOT NULL,
  subtitle text,
  formula_code varchar(80) NOT NULL DEFAULT 'diagnostico_geral_xlsx_v1',
  source_file_name varchar(255),
  source_sha256 varchar(64),
  display_config jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(display_config) = 'object'),
  created_by_user_id integer REFERENCES "user"(id) ON DELETE SET NULL,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (template_id, version_number),
  CHECK (NOT is_active OR status = 'published'),
  CHECK (btrim(title) <> ''),
  CHECK (btrim(formula_code) <> ''),
  CHECK (source_sha256 IS NULL OR source_sha256 ~ '^[0-9a-fA-F]{64}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS diagnostic_version_one_active_idx
  ON diagnostic_version(template_id) WHERE is_active = true;

CREATE TABLE IF NOT EXISTS diagnostic_section (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id bigint NOT NULL REFERENCES diagnostic_version(id) ON DELETE CASCADE,
  code varchar(30) NOT NULL,
  slug varchar(100) NOT NULL,
  name varchar(180) NOT NULL,
  source_sheet_name varchar(180),
  source_row integer,
  sort_order smallint NOT NULL,
  is_visible boolean NOT NULL DEFAULT true,
  is_growth_pillar boolean NOT NULL DEFAULT false,
  chart_config jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(chart_config) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (version_id, code),
  UNIQUE (version_id, slug),
  UNIQUE (version_id, sort_order),
  CHECK (btrim(code) <> ''),
  CHECK (btrim(slug) <> ''),
  CHECK (btrim(name) <> ''),
  CHECK (sort_order > 0)
);

CREATE TABLE IF NOT EXISTS diagnostic_question (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id bigint NOT NULL REFERENCES diagnostic_section(id) ON DELETE CASCADE,
  code varchar(20) NOT NULL,
  item_title varchar(255) NOT NULL,
  prompt text NOT NULL,
  sort_order smallint NOT NULL,
  max_score numeric(8,2) NOT NULL DEFAULT 10 CHECK (max_score >= 0),
  is_required boolean NOT NULL DEFAULT false,
  allows_not_applicable boolean NOT NULL DEFAULT true,
  source_row integer,
  display_config jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(display_config) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (section_id, code),
  UNIQUE (section_id, sort_order),
  CHECK (btrim(code) <> ''),
  CHECK (btrim(item_title) <> ''),
  CHECK (btrim(prompt) <> ''),
  CHECK (sort_order > 0)
);

CREATE TABLE IF NOT EXISTS diagnostic_evaluation_option (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id bigint NOT NULL REFERENCES diagnostic_version(id) ON DELETE CASCADE,
  code varchar(80) NOT NULL,
  label text NOT NULL,
  score numeric(8,2) NOT NULL CHECK (score BETWEEN 0 AND 10),
  sort_order smallint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (version_id, code),
  UNIQUE (version_id, label),
  UNIQUE (version_id, sort_order),
  CHECK (btrim(code) <> ''),
  CHECK (btrim(label) <> ''),
  CHECK (sort_order > 0)
);

CREATE TABLE IF NOT EXISTS diagnostic_recommendation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id bigint NOT NULL REFERENCES diagnostic_section(id) ON DELETE CASCADE,
  question_id bigint REFERENCES diagnostic_question(id) ON DELETE SET NULL,
  recommendation text NOT NULL,
  sort_order smallint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (section_id, sort_order),
  CHECK (btrim(recommendation) <> ''),
  CHECK (sort_order > 0)
);

CREATE TABLE IF NOT EXISTS diagnostic_submission (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id bigint NOT NULL REFERENCES diagnostic_version(id),
  public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  status varchar(30) NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'submitted', 'under_review', 'completed', 'archived')),
  company_name varchar(255) NOT NULL,
  company_document varchar(30),
  respondent_name varchar(255),
  respondent_email varchar(255),
  respondent_phone varchar(40),
  diagnostic_date date NOT NULL DEFAULT current_date,
  created_by_user_id integer REFERENCES "user"(id) ON DELETE SET NULL,
  assigned_to_user_id integer REFERENCES "user"(id) ON DELETE SET NULL,
  reviewed_by_user_id integer REFERENCES "user"(id) ON DELETE SET NULL,
  consent_accepted_at timestamptz,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  CHECK (btrim(company_name) <> ''),
  CHECK (company_document IS NULL OR btrim(company_document) <> ''),
  CHECK (respondent_email IS NULL OR respondent_email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')
);

CREATE INDEX IF NOT EXISTS diagnostic_submission_status_created_idx
  ON diagnostic_submission(status, created_at DESC);
CREATE INDEX IF NOT EXISTS diagnostic_submission_version_idx
  ON diagnostic_submission(version_id);
CREATE INDEX IF NOT EXISTS diagnostic_submission_company_name_idx
  ON diagnostic_submission(lower(company_name));
CREATE INDEX IF NOT EXISTS diagnostic_submission_date_idx
  ON diagnostic_submission(diagnostic_date DESC);

CREATE TABLE IF NOT EXISTS diagnostic_section_response (
  submission_id bigint NOT NULL REFERENCES diagnostic_submission(id) ON DELETE CASCADE,
  section_id bigint NOT NULL REFERENCES diagnostic_section(id),
  answers_responsible_name varchar(255),
  sector_responsible_name varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (submission_id, section_id)
);

CREATE TABLE IF NOT EXISTS diagnostic_answer (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id bigint NOT NULL REFERENCES diagnostic_submission(id) ON DELETE CASCADE,
  question_id bigint NOT NULL REFERENCES diagnostic_question(id),
  applicable boolean,
  self_score numeric(8,2) CHECK (self_score IS NULL OR self_score BETWEEN 0 AND 10),
  evaluation_option_id bigint REFERENCES diagnostic_evaluation_option(id),
  consultant_observation text,
  possible_improvements text,
  answered_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (submission_id, question_id)
);

CREATE INDEX IF NOT EXISTS diagnostic_answer_submission_idx ON diagnostic_answer(submission_id);

CREATE TABLE IF NOT EXISTS diagnostic_section_result (
  submission_id bigint NOT NULL REFERENCES diagnostic_submission(id) ON DELETE CASCADE,
  section_id bigint NOT NULL REFERENCES diagnostic_section(id),
  self_score_sum numeric(14,4) NOT NULL DEFAULT 0,
  consultant_score_sum numeric(14,4) NOT NULL DEFAULT 0,
  max_score_sum numeric(14,4) NOT NULL DEFAULT 0,
  score_ratio numeric(14,12) NOT NULL DEFAULT 0 CHECK (score_ratio BETWEEN 0 AND 1),
  gap_ratio numeric(14,12) GENERATED ALWAYS AS (1::numeric - score_ratio) STORED,
  calculation_code varchar(80) NOT NULL,
  calculated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (submission_id, section_id)
);

CREATE TABLE IF NOT EXISTS diagnostic_submission_result (
  submission_id bigint PRIMARY KEY REFERENCES diagnostic_submission(id) ON DELETE CASCADE,
  overall_score_ratio numeric(14,12) NOT NULL DEFAULT 0 CHECK (overall_score_ratio BETWEEN 0 AND 1),
  growth_pillars_ratio numeric(14,12) NOT NULL DEFAULT 0 CHECK (growth_pillars_ratio BETWEEN 0 AND 1),
  section_count smallint NOT NULL DEFAULT 10,
  growth_pillar_count smallint NOT NULL DEFAULT 4,
  calculation_code varchar(80) NOT NULL,
  calculated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS diagnostic_deliverable (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id bigint NOT NULL REFERENCES diagnostic_version(id) ON DELETE CASCADE,
  code varchar(20) NOT NULL,
  name varchar(255) NOT NULL,
  specification text NOT NULL,
  sort_order smallint NOT NULL,
  UNIQUE (version_id, code),
  UNIQUE (version_id, sort_order),
  CHECK (btrim(code) <> ''),
  CHECK (btrim(name) <> ''),
  CHECK (btrim(specification) <> ''),
  CHECK (sort_order > 0)
);

CREATE TABLE IF NOT EXISTS diagnostic_protocol (
  submission_id bigint PRIMARY KEY REFERENCES diagnostic_submission(id) ON DELETE CASCADE,
  recipient_company_name varchar(255) NOT NULL,
  recipient_company_document varchar(30),
  recipient_address text,
  consultant_company_name varchar(255),
  consultant_company_document varchar(30),
  city varchar(120),
  state varchar(2),
  delivery_date date,
  signer_name varchar(255),
  signed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Mantém updated_at correto mesmo quando a alteração não vier do app.
CREATE OR REPLACE FUNCTION diagnostic_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS diagnostic_version_touch_updated_at ON diagnostic_version;
CREATE TRIGGER diagnostic_version_touch_updated_at
BEFORE UPDATE ON diagnostic_version
FOR EACH ROW EXECUTE FUNCTION diagnostic_touch_updated_at();

DROP TRIGGER IF EXISTS diagnostic_submission_touch_updated_at ON diagnostic_submission;
CREATE TRIGGER diagnostic_submission_touch_updated_at
BEFORE UPDATE ON diagnostic_submission
FOR EACH ROW EXECUTE FUNCTION diagnostic_touch_updated_at();

DROP TRIGGER IF EXISTS diagnostic_section_response_touch_updated_at ON diagnostic_section_response;
CREATE TRIGGER diagnostic_section_response_touch_updated_at
BEFORE UPDATE ON diagnostic_section_response
FOR EACH ROW EXECUTE FUNCTION diagnostic_touch_updated_at();

DROP TRIGGER IF EXISTS diagnostic_answer_touch_updated_at ON diagnostic_answer;
CREATE TRIGGER diagnostic_answer_touch_updated_at
BEFORE UPDATE ON diagnostic_answer
FOR EACH ROW EXECUTE FUNCTION diagnostic_touch_updated_at();

DROP TRIGGER IF EXISTS diagnostic_protocol_touch_updated_at ON diagnostic_protocol;
CREATE TRIGGER diagnostic_protocol_touch_updated_at
BEFORE UPDATE ON diagnostic_protocol
FOR EACH ROW EXECUTE FUNCTION diagnostic_touch_updated_at();

-- Garante que submissão, seção, pergunta e opção sempre pertençam à mesma versão.
CREATE OR REPLACE FUNCTION diagnostic_validate_section_link()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  submission_version_id bigint;
  section_version_id bigint;
BEGIN
  SELECT version_id INTO submission_version_id
  FROM diagnostic_submission WHERE id = NEW.submission_id;

  SELECT version_id INTO section_version_id
  FROM diagnostic_section WHERE id = NEW.section_id;

  IF submission_version_id IS DISTINCT FROM section_version_id THEN
    RAISE EXCEPTION 'A seção não pertence à versão da submissão.' USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS diagnostic_section_response_validate_link ON diagnostic_section_response;
CREATE TRIGGER diagnostic_section_response_validate_link
BEFORE INSERT OR UPDATE OF submission_id, section_id ON diagnostic_section_response
FOR EACH ROW EXECUTE FUNCTION diagnostic_validate_section_link();

DROP TRIGGER IF EXISTS diagnostic_section_result_validate_link ON diagnostic_section_result;
CREATE TRIGGER diagnostic_section_result_validate_link
BEFORE INSERT OR UPDATE OF submission_id, section_id ON diagnostic_section_result
FOR EACH ROW EXECUTE FUNCTION diagnostic_validate_section_link();

CREATE OR REPLACE FUNCTION diagnostic_validate_answer_links()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  submission_version_id bigint;
  question_version_id bigint;
  option_version_id bigint;
BEGIN
  SELECT version_id INTO submission_version_id
  FROM diagnostic_submission WHERE id = NEW.submission_id;

  SELECT section.version_id INTO question_version_id
  FROM diagnostic_question question
  JOIN diagnostic_section section ON section.id = question.section_id
  WHERE question.id = NEW.question_id;

  IF submission_version_id IS DISTINCT FROM question_version_id THEN
    RAISE EXCEPTION 'A pergunta não pertence à versão da submissão.' USING ERRCODE = '23514';
  END IF;

  IF NEW.evaluation_option_id IS NOT NULL THEN
    SELECT version_id INTO option_version_id
    FROM diagnostic_evaluation_option WHERE id = NEW.evaluation_option_id;

    IF submission_version_id IS DISTINCT FROM option_version_id THEN
      RAISE EXCEPTION 'A opção de avaliação não pertence à versão da submissão.' USING ERRCODE = '23514';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS diagnostic_answer_validate_links ON diagnostic_answer;
CREATE TRIGGER diagnostic_answer_validate_links
BEFORE INSERT OR UPDATE OF submission_id, question_id, evaluation_option_id ON diagnostic_answer
FOR EACH ROW EXECUTE FUNCTION diagnostic_validate_answer_links();

CREATE OR REPLACE FUNCTION diagnostic_validate_recommendation_question()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  question_section_id bigint;
BEGIN
  IF NEW.question_id IS NOT NULL THEN
    SELECT section_id INTO question_section_id
    FROM diagnostic_question WHERE id = NEW.question_id;

    IF NEW.section_id IS DISTINCT FROM question_section_id THEN
      RAISE EXCEPTION 'A recomendação e a pergunta precisam pertencer à mesma seção.' USING ERRCODE = '23514';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS diagnostic_recommendation_validate_question ON diagnostic_recommendation;
CREATE TRIGGER diagnostic_recommendation_validate_question
BEFORE INSERT OR UPDATE OF section_id, question_id ON diagnostic_recommendation
FOR EACH ROW EXECUTE FUNCTION diagnostic_validate_recommendation_question();

-- Template/versionamento
INSERT INTO diagnostic_template (slug, name, description)
VALUES ('diagnostico-empresarial', 'Diagnóstico Empresarial', 'Reprodução fiel de diagnóstico geral.xlsx')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;

INSERT INTO diagnostic_version (
  template_id, version_number, status, is_active, title, subtitle, formula_code,
  source_file_name, source_sha256, display_config, published_at
)
SELECT
  id, 1, 'published', true, 'DIAGNÓSTICO EMPRESARIAL', 'QUESTIONÁRIO INICIAL',
  'diagnostico_geral_xlsx_v1', 'diagnóstico geral.xlsx',
  'dd4c7b65010d0280825e2b8df091c35eb05cd394ff4a92d260f11d6fd4545425',
  '{"palette":{"navy":"#1F2942","lightBlue":"#E5F8FF","cyan":"#56F0F8","chartBlue":"#002776","chartGreen":"#92D400"},"font":"Calibri","visibleSourceRows":["1:9","32:53","101:119"]}'::jsonb,
  now()
FROM diagnostic_template WHERE slug = 'diagnostico-empresarial'
ON CONFLICT (template_id, version_number) DO UPDATE SET
  status = EXCLUDED.status,
  is_active = EXCLUDED.is_active,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  formula_code = EXCLUDED.formula_code,
  source_file_name = EXCLUDED.source_file_name,
  source_sha256 = EXCLUDED.source_sha256,
  display_config = EXCLUDED.display_config,
  updated_at = now();

-- Escala equivalente à aba LISTAS
INSERT INTO diagnostic_evaluation_option (version_id, code, label, score, sort_order)
SELECT version.id, option.code, option.label, option.score, option.sort_order
FROM diagnostic_version version
JOIN diagnostic_template template ON template.id = version.template_id
CROSS JOIN (VALUES
  ('nao_existe', 'NÃO EXISTE', 0::numeric, 1::smallint),
  ('informal', 'EXISTE (MAS INFORMALMENTE)', 3::numeric, 2::smallint),
  ('padronizada', 'EXISTE DE FORMA PADRONIZADA (MAS PODE SER MELHORADO)', 7::numeric, 3::smallint),
  ('perfeita', 'EXISTE E FUNCIONA PERFEITAMENTE', 10::numeric, 4::smallint)
) AS option(code, label, score, sort_order)
WHERE template.slug = 'diagnostico-empresarial' AND version.version_number = 1
ON CONFLICT (version_id, code) DO UPDATE SET
  label = EXCLUDED.label, score = EXCLUDED.score, sort_order = EXCLUDED.sort_order;

-- Dez perspectivas; somente quatro eram visíveis no questionário da planilha.
INSERT INTO diagnostic_section (
  version_id, code, slug, name, source_sheet_name, source_row, sort_order,
  is_visible, is_growth_pillar, chart_config
)
SELECT version.id, section.code, section.slug, section.name, section.sheet, section.source_row,
       section.sort_order, section.is_visible, section.is_pillar,
       '{"realColor":"#1F2942","gapColor":"#92D400","radarColor":"#002776"}'::jsonb
FROM diagnostic_version version
JOIN diagnostic_template template ON template.id = version.template_id
CROSS JOIN (VALUES
  ('societario', 'societario', 'Societário', 'Societário', 10, 1, false, false),
  ('tecnologia', 'tecnologia', 'Tecnologia', 'Tecnologia', 22, 2, false, false),
  ('comercial', 'comercial', 'Comercial', 'Comercial', 33, 3, true, true),
  ('marketing', 'marketing', 'Marketing', 'Marketing', 45, 4, true, true),
  ('financeiro', 'financeiro', 'Financeiro', 'Financeiro', 54, 5, false, false),
  ('controladoria', 'controladoria', 'Controladoria', 'Controladoria', 67, 6, false, false),
  ('fiscal', 'fiscal', 'Fiscal', 'Fiscal', 82, 7, false, false),
  ('contabil', 'contabil', 'Contábil', 'Contábil', 92, 8, false, false),
  ('gestao_pessoas', 'gestao-pessoas', 'Gestão de Pessoas', 'Pessoas', 102, 9, true, true),
  ('estrategia', 'estrategia', 'Estratégia', 'Estratégia', 112, 10, true, true)
) AS section(code, slug, name, sheet, source_row, sort_order, is_visible, is_pillar)
WHERE template.slug = 'diagnostico-empresarial' AND version.version_number = 1
ON CONFLICT (version_id, code) DO UPDATE SET
  slug = EXCLUDED.slug, name = EXCLUDED.name, source_sheet_name = EXCLUDED.source_sheet_name,
  source_row = EXCLUDED.source_row, sort_order = EXCLUDED.sort_order,
  is_visible = EXCLUDED.is_visible, is_growth_pillar = EXCLUDED.is_growth_pillar,
  chart_config = EXCLUDED.chart_config;

-- Catálogo literal das 51 perguntas. Erros ortográficos da fonte foram preservados.
INSERT INTO diagnostic_question (
  section_id, code, item_title, prompt, sort_order, max_score,
  is_required, allows_not_applicable, source_row
)
SELECT section.id, question.code, question.item_title, question.prompt,
       question.sort_order, 10, false, true, question.source_row
FROM diagnostic_section section
JOIN diagnostic_version version ON version.id = section.version_id
JOIN diagnostic_template template ON template.id = version.template_id
JOIN (VALUES
  ('societario', '1.1', 'Formalização da sociedade', 'A sociedade está devidamente formalizada em contrato social?', 1, 15),
  ('societario', '1.2', 'Quotas da sociedade', 'Todos os sócios possuem ciências das quotas de cada sócio dentro do negócio?', 2, 16),
  ('societario', '1.3', 'Governança', 'São realizadas reuniões mensais com os sócios para análise dos resultados?', 3, 17),
  ('societario', '1.4', 'Separação das Finanças', 'Há separação clara dos gastos da pessoa física dos gastos da pessoa jurídica (empresa)?', 4, 18),
  ('societario', '1.5', 'Pró-Labore', 'Existe definição do pró-labore mensal dos sócios através de um critério profissional?', 5, 19),
  ('societario', '1.6', 'Distribuição de Lucros', 'Existe uma política estabelecida com relação a periodicidade e critério de % na distribuição de lucros?', 6, 20),
  ('tecnologia', '2.1', 'Sistemas', 'A empresa possui sistema para dar suporte à gestão empresarial (ERP), buscando simplificar e automatizar tarefas e ações operacionais?', 1, 27),
  ('tecnologia', '2.2', 'Suporte', 'Há treinamento e suporte contínuo quanto ao uso do sistema de gestão (ERP) e outras tecnologias dentro do negócio?', 2, 28),
  ('tecnologia', '2.3', 'Segurança e Backup', 'Existe rotina periódica de backup onde os dados da empresa estão armazenados?', 3, 29),
  ('tecnologia', '2.4', 'Infraestrutura', 'A empresa possui equipamentos suficientes que suportem ao bom funcionamento da gestão empresarial?', 4, 30),
  ('tecnologia', '2.5', 'Automação', 'Existe integração entre a atividade fim do negócio e as atividades financeiras (vendas, compras, estoque, faturamento, contas a receber, cobrança, contas a pagar, relatórios)?', 5, 31),
  ('comercial', '3.1', 'Meta de Vendas', 'A empresa possui clareza sobre a meta de faturamento necessária para atingir os objetivos desejados pelos sócios?', 1, 38),
  ('comercial', '3.2', 'CRM', 'A empresa possui sistema de relacionamento com o cliente que ajude no atingimento da meta de vendas?', 2, 39),
  ('comercial', '3.3', 'Precificação dos Serviços', 'Existe metodologia para precificar os produtos/serviços prestados?', 3, 40),
  ('comercial', '3.4', 'Relatórios', 'Existem relatórios que dão suporte ao acompanhamento diário, semanal e/ou mensal das vendas?', 4, 41),
  ('comercial', '3.5', 'Governança', 'Há reuniões mensais com equipe comercial para apresentação e avaliação dos resultados?', 5, 42),
  ('comercial', '3.6', 'Indicadores', 'Existem indicadores de vendas (como número de propostas, taxa de conversão, ticket médio e outros indicadores comerciais)?', 6, 43),
  ('marketing', '4.1', 'Planejamento', 'Há um plano de comunicação aos potenciais clientes que esteja vinculado aos objetivos comerciais?', 1, 50),
  ('marketing', '4.2', 'Assessoria de Marketing', 'Há um time interno/terceirizado dedicado a pensar as ações de marketing? ', 2, 51),
  ('marketing', '4.3', 'Endomarketing', 'A equipe conhece as principais metas e ações de marketing da empresa?', 3, 52),
  ('financeiro', '5.1', 'Plano de Contas', 'Existe um plano de contas gerencial, separando os grupos de receitas dos grupos de gastos?', 1, 59),
  ('financeiro', '5.2', 'Contas a Pagar', 'Todas as movimentações relativas às obrigações com fornecedores, colaboradores, governo estão devidamente registrados e controladas no sistema de gestão financeira?', 2, 60),
  ('financeiro', '5.3', 'Contas a Receber', 'Todas as movimentações relativas aos direitos de recebimento das vendas estão devidamente registradas e controlados no sistema de gestão financeira?', 3, 61),
  ('financeiro', '5.4', 'Conciliação Bancária', 'A conciliação bancária está em dia? Os saldos dos bancos, caixinha e fundo fixo são devidamente atualizados no sistema diariamente?', 4, 62),
  ('financeiro', '5.5', 'Fluxo de Caixa', 'A empresa possui um demonstrativo mensal dos recebimentos x pagamentos que permite a análise e a projeção, auxiliando na tomada de decisões baseadas em informação real e confiável?', 5, 63),
  ('financeiro', '5.6', 'Crédito e Cobrança', 'Há uma política clara de fornecimento de crédito, forma de recebimentos e acompanhamento da cobrança aos clientes?', 6, 64),
  ('financeiro', '5.7', 'Relatórios', 'Existem relatórios que dão suporte ao acompanhamento das movimentações financeiras periodicamente (diário, semanal e mensal)?', 7, 65),
  ('controladoria', '6.1', 'Capital de Giro', 'A empresa possui capital de giro suficiente para cobrir pelo menos 4 meses da sua operação?', 1, 72),
  ('controladoria', '6.2', 'Meta Financeira', 'A empresa possui clareza sobre a meta financeira necessária para atingir os objetivos empresariais e desejados pelos sócios?', 2, 73),
  ('controladoria', '6.3', 'Orçamento', 'Existe planejamento orçamentário para projeção dos resultados (DRE) a serem alcançados?', 3, 74),
  ('controladoria', '6.4', 'Ponto de Equilíbrio', 'A empresa sabe qual é o ponto de equilíbrio do negócio (receita mínima necessária para não ter prejuízo)?', 4, 75),
  ('controladoria', '6.5', 'Gestão Orçamentária', 'Existe acompanhamento do planejamento orçamentário com os resultados previstos sendo confrontados com os resultados realizados?', 5, 76),
  ('controladoria', '6.6', 'Gestão de Custos e Despesas', 'Existe método para realizar uma gestão e controle efetivo de custos fixos e váriaveis mensais?', 6, 77),
  ('controladoria', '6.7', 'Análise Vertical / Horizontal', 'Existe análise dos grupos de contas (receitas e gastos) relativos ao mês anterior?', 7, 78),
  ('controladoria', '6.8', 'Indicadores', 'Existem indicadores econômicos e financeiros (como margem de contribuição, margem líquida, geração de caixa, outro)?', 8, 79),
  ('controladoria', '6.9', 'Relatórios', 'Existem relatórios que dão suporte ao acompanhamento dos resultados mensais?', 9, 80),
  ('fiscal', '7.1', 'Planejamento Tributário', 'A tributação da empresa está enquadrada no melhor regime tributário para a sua atividade econômica?', 1, 87),
  ('fiscal', '7.2', 'Recolhimento de Tributos', 'Os impostos e taxas são pagos rigorosamente em dia?', 2, 88),
  ('fiscal', '7.3', 'Apuração Fiscal', 'A empresa realiza apuração de 100% das suas vendas?', 3, 89),
  ('fiscal', '7.4', 'Automação', 'Existe integração fiscal (faturamento) com as atividades financeiras (faturamento, contas a receber, cobrança e contas a pagar)?', 4, 90),
  ('contabil', '8.1', 'Balancete e DRE', 'A empresa recebe mensalmente o balancete e DRE da contabilidade (até o dia 15 de cada mês, pelo menos)?', 1, 97),
  ('contabil', '8.2', 'Automação', 'Existe integração contábil (movimentações de débitos e créditos) com as atividades financeiras (faturamento, contas a receber, cobrança e contas a pagar)?', 2, 98),
  ('contabil', '8.3', 'Documentação', 'Os documentos das movimentações de entradas e saídas (notas fiscais, cupons fiscais, recibos, comprovantes de pagamentos, contratos) estão devidamente organizados?', 3, 99),
  ('contabil', '8.4', 'Planejamento', 'É realizada reunião periódica com a contabilidade para obtenção de oportunidades ou identificação de pontos de melhorias?', 4, 100),
  ('gestao_pessoas', '9.1', 'Plano de Cargos e Salários', 'Existe um plano de cargos e salários escrito e documentado, que é praticado e conhecido por todos os colaboradores nos seus respectivos níveis dentro da organização?', 1, 107),
  ('gestao_pessoas', '9.2', 'Benefícios', 'Existe algum plano de benefícios na empresa (plano de saúde, odontológico, reembolso de academia, outro)?', 2, 108),
  ('gestao_pessoas', '9.3', 'Obrigações Trabalhistas', 'A apuração e o recolhimento dos encargos sociais são pagos rigorosamente em dia?', 3, 109),
  ('gestao_pessoas', '9.4', 'PLR', 'Existe alguma iniciativa para premiação através de Participação nos Lucros e Resultados? E existe um Modelo de Remuneração Estratégica ou Participação nos Resultados?', 4, 110),
  ('estrategia', '10.1', 'Inovação', 'Existe planejamento de criação de novos produtos/serviços ou novas linhas de receitas?', 1, 117),
  ('estrategia', '10.2', 'Crescimento e Expansão', 'Existe um planejamento de médio e longo prazo para crescimento e expansão do negócio, que está registrado num plano de ação que é acompanhado consistentemente?', 2, 118),
  ('estrategia', '10.3', 'Estratégia', 'As estratégia de curto, médio e longo prazo são anualmente revisadas e construídas de forma estruturada através de um processo organizado de forma coletiva e aprovada pelos sócios da organização? Elas são compartilhadas e desdobradas corretamente para todos os níveis da organização?', 3, 119)
) AS question(section_code, code, item_title, prompt, sort_order, source_row)
  ON question.section_code = section.code
WHERE template.slug = 'diagnostico-empresarial' AND version.version_number = 1
ON CONFLICT (section_id, code) DO UPDATE SET
  item_title = EXCLUDED.item_title, prompt = EXCLUDED.prompt,
  sort_order = EXCLUDED.sort_order, max_score = EXCLUDED.max_score,
  source_row = EXCLUDED.source_row;

-- 48 oportunidades estáticas: a planilha sempre as exibe, sem condicioná-las às notas.
INSERT INTO diagnostic_recommendation (section_id, recommendation, sort_order)
SELECT section.id, recommendation.text, recommendation.sort_order
FROM diagnostic_section section
JOIN diagnostic_version version ON version.id = section.version_id
JOIN diagnostic_template template ON template.id = version.template_id
JOIN (VALUES
  ('societario', 'Recomendar a formalização dos sócios que não constam em contrato social', 1),
  ('societario', 'Definir quotas sociais e os percentuais entre os sócios', 2),
  ('societario', 'Realizar reunião mensal com os sócios e diretores para acompanhamento dos resultados alcançados em todas as esferas', 3),
  ('societario', 'Definir critérios e valores de pró-labores para os sócios que possuem função executiva no negócio', 4),
  ('societario', 'Definir critérios, valores e periodicidade para a distribuição de lucros (quando houver)', 5),
  ('tecnologia', 'Recomendar implantação de um software de gestão financeira capaz de realizar o controle das movimentações de entradas e saídas', 1),
  ('tecnologia', 'Sugerir programa de treinamento contínuo para os colaboradores', 2),
  ('tecnologia', 'Recomendar manter os dados em ambiente protegido (preferencial em nuvem)', 3),
  ('tecnologia', 'Recomendar integração e automação das atividades financeiras do negócio', 4),
  ('comercial', 'Registrar nesta perspectiva o faturamento atual do cliente para medir o crescimento', 1),
  ('comercial', 'Recomendar o uso de um CRM para apoio no atingimento das metas comerciais que garantirão o resultado financeiro', 2),
  ('comercial', 'Elaborar método de precificação para cada tipo de produto/serviço', 3),
  ('comercial', 'Recomendar relatórios de vendas para a equipe comercial/sócios possam acompanhar as meta comerciais', 4),
  ('comercial', 'Recomendar reuniões de acompanhamento para a equipe de de vendas/comercial', 5),
  ('comercial', 'Recomendar implantação de indicadores comerciais', 6),
  ('marketing', 'Elaborar objetivos e metas de Retorno Sobre Investimento em Markting para os próximos 12 meses', 1),
  ('marketing', 'Contratar assessoria de marketing (colaborador exclusivo ou empresa terceirizada)', 2),
  ('marketing', 'Divulgar o planejamento das ações para os colaboradores através de uma agenda fixa (semanal, mensal, anual)', 3),
  ('financeiro', 'Estruturar um plano de contas gerencial para o negócio', 1),
  ('financeiro', 'Definir rotinas e processos do contas a pagar', 2),
  ('financeiro', 'Definir rotinas e processos do contas a receber', 3),
  ('financeiro', 'Estruturar processo de conferência e conciliação bancária diária', 4),
  ('financeiro', 'Implantar o fluxo de caixa (diário, semanal, quinzenal, mensal, anual)', 5),
  ('financeiro', 'Elaborar políticas de crédito especificando formas de pagamento e limites para determinados perfis de clientes', 6),
  ('financeiro', 'Recomendar relatórios financeiros através do software de gestão que possam auxiliar no atingimento das metas de resultado', 7),
  ('controladoria', 'Definir em valor (R$) quanto a empresa precisa ter em caixa para suportar no mínimo 4 meses sem vendas (reserva de emergência)', 1),
  ('controladoria', 'Definir a meta de resultado - DRE (mensal, semestral e anual)', 2),
  ('controladoria', 'Acompanhar o orçamento mensalmente (DRE e Caixa)', 3),
  ('controladoria', 'Definir Ponto de Equilíbrio Econômico', 4),
  ('controladoria', 'Realizar acompanhamento de orçado vs realizado', 5),
  ('controladoria', 'Realizar análises verticais e horizontais dos grupos de contas e análise das variações', 6),
  ('controladoria', 'Recomendar implantação de indicadores financeiros (Margem de Contribuição, EBITDA, Lucratividade, SG&A)', 7),
  ('fiscal', 'Acionar contabilidade para validação do melhor regime de tribuitação (Planejamento Tributário)', 1),
  ('fiscal', 'Realizar o recolhimento dos tributos mensalmente ou a medida que houver o fato gerador', 2),
  ('fiscal', 'Realizar a apuração fiscal de 100% das vendas', 3),
  ('fiscal', 'Recomendar automação entre o módulo de vendas (faturamento) e o financeiro', 4),
  ('contabil', 'Solicitar balancete e DRE contábil da contabilidade mensalmente', 1),
  ('contabil', 'Realizar análise entre DRE do financeiro/controladoria e da contabilidade', 2),
  ('contabil', 'Enviar mensalmente os extratos bancários e documentos comprobatórios (notas fiscais, contratos, cupons fiscais) para a contabilidade', 3),
  ('contabil', 'Realizar reunião mensal com a contabilidade para cumprimento das obrigações acessórias', 4),
  ('gestao_pessoas', 'Sugerir premiações aos colaboradores mediante atingimento de resultados anuais', 1),
  ('gestao_pessoas', 'Sugerir benefícios como reembolso de academia, plano de saúde, plano odontológico, seguro de vida aos colaboradores', 2),
  ('gestao_pessoas', 'Realizar o recolhimento de todas as obrigações e encargos trabalhistas (a fim de evitar qualquer ação futura contra a empresa)', 3),
  ('estrategia', 'Elaborar planos para novos serviços ou de expansão para novas praças', 1),
  ('estrategia', 'Analisar Forças, Fraquezas, Ameaças e Oportunidades do setor (SWOT/FOFA)', 2),
  ('estrategia', 'Desenhar o Plano de Negócios (Canvas)', 3),
  ('estrategia', 'Elaborar a viabilidade econômico-financeiro de uma nova unidade/filial da empresa cliente', 4),
  ('estrategia', 'Definir as metas para atingir os objetivos da empresa e dos sócios', 5)
) AS recommendation(section_code, text, sort_order)
  ON recommendation.section_code = section.code
WHERE template.slug = 'diagnostico-empresarial' AND version.version_number = 1
ON CONFLICT (section_id, sort_order) DO UPDATE SET recommendation = EXCLUDED.recommendation;

-- Conteúdo estático da aba Protocolo.
INSERT INTO diagnostic_deliverable (version_id, code, name, specification, sort_order)
SELECT version.id, deliverable.code, deliverable.name, deliverable.specification, deliverable.sort_order
FROM diagnostic_version version
JOIN diagnostic_template template ON template.id = version.template_id
CROSS JOIN (VALUES
  ('1.0', 'Relatório de Diagnóstico', 'Este documento contempla: a) os resultados obtidos da EMPRESA XXX; b) sugestões de melhorias nos aspectos abordados no processo de diagnóstico.', 1),
  ('2.0', 'Apresentação Final do Diagnóstico realizado para a Diretoria', 'Este documento contempla: a) Sumário Executivo; b) Análise de Evidências Financeiras; c) Conclusões e Recomendações; e d) Proposta de Contrato de Consultoria em Gestão.', 2),
  ('3.0', 'Mídia com as informações entregues', 'Esta mídia contempla: arquivo em .pdf da Apresentação Final do Diagnóstico e Relatório de Diagnóstico', 3)
) AS deliverable(code, name, specification, sort_order)
WHERE template.slug = 'diagnostico-empresarial' AND version.version_number = 1
ON CONFLICT (version_id, code) DO UPDATE SET
  name = EXCLUDED.name, specification = EXCLUDED.specification, sort_order = EXCLUDED.sort_order;

COMMIT;
