-- Nexus · Diagnóstico de Operações fixo
--
-- Migration idempotente para PostgreSQL/Neon. O catálogo e as fórmulas ficam em
-- lib/operationsDiagnosticCatalog.js; estas tabelas armazenam somente os dados
-- do diagnóstico operacional e não possuem vínculo com o diagnóstico geral.

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('nexus:operations-diagnostics:fixed:v1'));

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS operations_diagnostic_submission (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  status varchar(30) NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'submitted', 'under_review', 'completed', 'archived')),
  company_name varchar(255) NOT NULL,
  diagnostic_date date NOT NULL DEFAULT current_date,
  template_code varchar(80) NOT NULL DEFAULT 'diagnostico-operacoes',
  template_version smallint NOT NULL DEFAULT 1 CHECK (template_version > 0),
  formula_code varchar(80) NOT NULL DEFAULT 'diagnostico_operacoes_fixo_v1',
  submitted_at timestamptz,
  reviewed_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (btrim(company_name) <> ''),
  CHECK (btrim(template_code) <> ''),
  CHECK (btrim(formula_code) <> '')
);

CREATE INDEX IF NOT EXISTS operations_diag_submission_status_created_idx
  ON operations_diagnostic_submission(status, created_at DESC);
CREATE INDEX IF NOT EXISTS operations_diag_submission_company_name_idx
  ON operations_diagnostic_submission(lower(company_name));
CREATE INDEX IF NOT EXISTS operations_diag_submission_date_idx
  ON operations_diagnostic_submission(diagnostic_date DESC);

CREATE TABLE IF NOT EXISTS operations_diagnostic_section_response (
  submission_id bigint NOT NULL
    REFERENCES operations_diagnostic_submission(id) ON DELETE CASCADE,
  section_code varchar(30) NOT NULL,
  submitted_answers_responsible_name varchar(255),
  submitted_sector_responsible_name varchar(255),
  answers_responsible_name varchar(255),
  sector_responsible_name varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (submission_id, section_code),
  CHECK (section_code IN (
    'comercial', 'churn', 'marketing', 'customer_success', 'atendimento', 'rh_cultura'
  ))
);

CREATE TABLE IF NOT EXISTS operations_diagnostic_answer (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id bigint NOT NULL
    REFERENCES operations_diagnostic_submission(id) ON DELETE CASCADE,
  question_code varchar(40) NOT NULL,
  submitted_evaluation_code varchar(20) NOT NULL,
  submitted_implementation_date date,
  submitted_will_implement boolean,
  submitted_notes text NOT NULL DEFAULT '',
  evaluation_code varchar(20) NOT NULL,
  implementation_date date,
  will_implement boolean,
  notes text NOT NULL DEFAULT '',
  answered_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (submission_id, question_code),
  CHECK (submitted_evaluation_code IN ('sim', 'revisar', 'nao')),
  CHECK (evaluation_code IN ('sim', 'revisar', 'nao')),
  CHECK (char_length(submitted_notes) <= 1200),
  CHECK (char_length(notes) <= 1200),
  CHECK ((
    (question_code ~ '^comercial\.[0-9]{3}$'
      AND substring(question_code FROM '[0-9]{3}$')::integer BETWEEN 1 AND 63)
    OR (question_code ~ '^churn\.[0-9]{3}$'
      AND substring(question_code FROM '[0-9]{3}$')::integer BETWEEN 1 AND 31)
    OR (question_code ~ '^marketing\.[0-9]{3}$'
      AND substring(question_code FROM '[0-9]{3}$')::integer BETWEEN 1 AND 52)
    OR (question_code ~ '^customer_success\.[0-9]{3}$'
      AND substring(question_code FROM '[0-9]{3}$')::integer BETWEEN 1 AND 15)
    OR (question_code ~ '^atendimento\.[0-9]{3}$'
      AND substring(question_code FROM '[0-9]{3}$')::integer BETWEEN 1 AND 17)
    OR (question_code ~ '^rh_cultura\.[0-9]{3}$'
      AND substring(question_code FROM '[0-9]{3}$')::integer BETWEEN 1 AND 48)
  ) IS TRUE),
  CHECK (
    (
      split_part(question_code, '.', 1) = 'comercial'
      AND submitted_implementation_date IS NULL
      AND submitted_will_implement IS NULL
      AND implementation_date IS NULL
      AND will_implement IS NULL
    )
    OR (
      split_part(question_code, '.', 1) IN ('churn', 'marketing', 'rh_cultura')
      AND submitted_will_implement IS NULL
      AND will_implement IS NULL
    )
    OR (
      split_part(question_code, '.', 1) IN ('customer_success', 'atendimento')
      AND submitted_implementation_date IS NULL
      AND implementation_date IS NULL
    )
  )
);

CREATE INDEX IF NOT EXISTS operations_diag_answer_submission_idx
  ON operations_diagnostic_answer(submission_id);
CREATE INDEX IF NOT EXISTS operations_diag_answer_evaluation_idx
  ON operations_diagnostic_answer(submission_id, evaluation_code);

CREATE TABLE IF NOT EXISTS operations_diagnostic_section_result (
  submission_id bigint NOT NULL
    REFERENCES operations_diagnostic_submission(id) ON DELETE CASCADE,
  section_code varchar(30) NOT NULL,
  score_sum numeric(14,4) NOT NULL DEFAULT 0 CHECK (score_sum >= 0),
  max_score_sum numeric(14,4) NOT NULL CHECK (max_score_sum > 0),
  score_ratio numeric(14,12) NOT NULL DEFAULT 0 CHECK (score_ratio BETWEEN 0 AND 1),
  gap_ratio numeric(14,12) GENERATED ALWAYS AS (1::numeric - score_ratio) STORED,
  answered_count smallint NOT NULL DEFAULT 0 CHECK (answered_count >= 0),
  total_question_count smallint NOT NULL CHECK (total_question_count > 0),
  calculation_code varchar(80) NOT NULL DEFAULT 'diagnostico_operacoes_fixo_v1',
  calculated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (submission_id, section_code),
  CHECK (section_code IN (
    'comercial', 'churn', 'marketing', 'customer_success', 'atendimento', 'rh_cultura'
  )),
  CHECK (score_sum <= max_score_sum),
  CHECK (answered_count <= total_question_count),
  CHECK (btrim(calculation_code) <> '')
);

CREATE TABLE IF NOT EXISTS operations_diagnostic_submission_result (
  submission_id bigint PRIMARY KEY
    REFERENCES operations_diagnostic_submission(id) ON DELETE CASCADE,
  overall_score_ratio numeric(14,12) NOT NULL DEFAULT 0
    CHECK (overall_score_ratio BETWEEN 0 AND 1),
  score_sum numeric(14,4) NOT NULL DEFAULT 0 CHECK (score_sum >= 0),
  max_score_sum numeric(14,4) NOT NULL DEFAULT 60 CHECK (max_score_sum > 0),
  item_score_sum numeric(14,4) NOT NULL DEFAULT 0 CHECK (item_score_sum >= 0),
  item_max_score_sum numeric(14,4) NOT NULL DEFAULT 2260 CHECK (item_max_score_sum > 0),
  section_count smallint NOT NULL DEFAULT 6 CHECK (section_count = 6),
  answered_count smallint NOT NULL DEFAULT 0 CHECK (answered_count >= 0),
  total_question_count smallint NOT NULL DEFAULT 226 CHECK (total_question_count = 226),
  progress_ratio numeric(14,12) GENERATED ALWAYS AS (
    answered_count::numeric / total_question_count::numeric
  ) STORED,
  calculation_code varchar(80) NOT NULL DEFAULT 'diagnostico_operacoes_fixo_v1',
  calculated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (score_sum <= max_score_sum),
  CHECK (item_score_sum <= item_max_score_sum),
  CHECK (answered_count <= total_question_count),
  CHECK (btrim(calculation_code) <> '')
);

CREATE OR REPLACE FUNCTION operations_diagnostic_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS operations_diag_submission_touch ON operations_diagnostic_submission;
CREATE TRIGGER operations_diag_submission_touch
BEFORE UPDATE ON operations_diagnostic_submission
FOR EACH ROW EXECUTE FUNCTION operations_diagnostic_touch_updated_at();

DROP TRIGGER IF EXISTS operations_diag_section_response_touch
  ON operations_diagnostic_section_response;
CREATE TRIGGER operations_diag_section_response_touch
BEFORE UPDATE ON operations_diagnostic_section_response
FOR EACH ROW EXECUTE FUNCTION operations_diagnostic_touch_updated_at();

DROP TRIGGER IF EXISTS operations_diag_answer_touch ON operations_diagnostic_answer;
CREATE TRIGGER operations_diag_answer_touch
BEFORE UPDATE ON operations_diagnostic_answer
FOR EACH ROW EXECUTE FUNCTION operations_diagnostic_touch_updated_at();

COMMENT ON TABLE operations_diagnostic_submission IS
  'Submissões exclusivas do Diagnóstico de Operações; não compartilha dados com diagnostic_submission.';
COMMENT ON COLUMN operations_diagnostic_answer.submitted_evaluation_code IS
  'Avaliação original e imutável recebida pelo formulário público.';
COMMENT ON COLUMN operations_diagnostic_answer.evaluation_code IS
  'Avaliação corrente, editável durante a revisão administrativa.';

COMMIT;
